version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - 80:80
  db-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: verystrongPassword123
    ports:
      - 1433:1433
      - 1434:1434
    volumes:
      - universitymssqlsystem:/var/opt/mssql
      - universitymssqluser:/var/opt/sqlserver
volumes:
  universitymssqlsystem:
  universitymssqluser: